homework1:
  alpha_range: [20, 360] # диапазон изменения параметра alpha
  beta_range: [0.2, 1]        # диапазон изменения параметра beta
  gamma_range: [0.2, 1]   # диапазон изменения параметра gamma
  delta_range: [0.2, 1]       # диапазон изменения параметра delta
homework3:
  input_image_path: data/puppy.png
  output_image_path: data/output.png
  opencv_output_image_path: data/cv_output.png
  sigma_space: 15
  sigma_color: 15
homework2:
  image_name: saturn_rings.png # поиск из папки data
<<<<<<< HEAD
=======
homework4:
  input_image: data/building.png
  sigma: 3.5
  thresh_percent: 0.2
  threshold: 5
  max_trials: 5000
  seed: 0xC0FFEE
  outpug_image: data/line_ransac.jpg
  output_edges: data/marr_hildreth_edges.jpg
>>>>>>> b351346 (init)
