homework1: 
    src_points:
        point1:
            x: 5
            y: 100
        point2:
            x: 320
            y: 10
        point3:
            x: 290
            y: 450
        point4:
            x: 20
            y: 400
    dst_size:
        h: 1300
        w: 1500
    colorjitter:
        hue: 280
        saturation: 0.4
        contrast: 0.5
        brightness: 0.8