homework1:
  alpha_range: [20, 180] # диапазон изменения параметра alpha
  beta_range: [0.2, 1]        # диапазон изменения параметра beta
  gamma_range: [0.2, 1]   # диапазон изменения параметра gamma
  delta_range: [0.2, 1]       # диапазон изменения параметра delta